#!/bin/python3

#Sockets, what they are and how they connect nodes together.  For port scanners as an example.

import socket

HOST = '127.0.0.1'
PORT = 7777

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM) #VERY COMMON SYNTAX AF_INET=IPV4 SOCK_STREAM=PORT
s.connect((HOST,PORT))
