#!/bin/python

import sys
import socket
from datetime import datetime

#Defining our target
if len(sys.argv)  == 2:
    target = socket.gethostbyname(sys.argv[1]) #Translate Hostname to IPv4

else:
    print("Invalid amount of arguments.")
    print("Syntax - python3 SkyScanner.py <ip>")

#Add a nice banner Very important for visual 
print("-" * 77)
print("Scanning target "+target)
print("Time started: "+str(datetime.now()))
print("-" * 77)

try:
    for port in range(1,65535):
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        socket.setdefaulttimeout(1)
        result = s.connect_ex((target,port)) #returns an error indicator for your scanner
        if result == 0:
            print("Port {} is open".format(port))
        s.close()

except KeyboardInterrupt:
        print("\nExiting program.")
        sys.exit()

except socket.gaierror:
        print("Hostname could not be resolved.")

except socket.error:
        print("Couldn't connect to server.")
        sys.exti()
